-- CartCheck database shape. Safe to run repeatedly against a database that
-- does not contain the retired sightings application tables.
-- Keep this file in sync with the numbered migrations.

CREATE SCHEMA IF NOT EXISTS cartcheck;

CREATE TABLE IF NOT EXISTS cartcheck.users (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email              TEXT NOT NULL UNIQUE,
  password_hash      TEXT NOT NULL,
  preferred_currency TEXT NOT NULL DEFAULT 'PHP'
                       CHECK (preferred_currency IN ('PHP', 'USD', 'EUR')),
  email_verified     BOOLEAN NOT NULL DEFAULT false,
  legacy_verification_exempt BOOLEAN NOT NULL DEFAULT false,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT users_email_normalized CHECK (
    email = lower(email) AND email = btrim(email) AND length(email) BETWEEN 3 AND 320
  )
);

CREATE TABLE IF NOT EXISTS cartcheck.sessions (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL REFERENCES cartcheck.users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cartcheck.auth_action_tokens (
  token_hash TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES cartcheck.users(id) ON DELETE CASCADE,
  purpose TEXT NOT NULL CHECK (purpose IN ('verify_email', 'reset_password')),
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS cartcheck.auth_email_limits (
  user_id BIGINT NOT NULL REFERENCES cartcheck.users(id) ON DELETE CASCADE,
  purpose TEXT NOT NULL CHECK (purpose IN ('verify_email', 'reset_password')),
  last_sent_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (user_id, purpose)
);

CREATE TABLE IF NOT EXISTS cartcheck.starter_products (
  code       TEXT PRIMARY KEY,
  name       TEXT NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 120),
  category   TEXT NOT NULL CHECK (length(btrim(category)) BETWEEN 1 AND 80),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS cartcheck.products (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id             BIGINT NOT NULL REFERENCES cartcheck.users(id) ON DELETE CASCADE,
  source_starter_code TEXT REFERENCES cartcheck.starter_products(code) ON DELETE SET NULL,
  name                TEXT NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 120),
  category            TEXT NOT NULL CHECK (length(btrim(category)) BETWEEN 1 AND 80),
  image_url           TEXT CHECK (image_url IS NULL OR length(image_url) <= 2048),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT products_id_user_unique UNIQUE (id, user_id),
  CONSTRAINT products_user_source_unique UNIQUE (user_id, source_starter_code)
);

CREATE TABLE IF NOT EXISTS cartcheck.shopping_trips (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      BIGINT NOT NULL REFERENCES cartcheck.users(id) ON DELETE CASCADE,
  status       TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed')),
  currency     TEXT NOT NULL CHECK (currency IN ('PHP', 'USD', 'EUR')),
  budget       NUMERIC(12, 2) CHECK (budget IS NULL OR budget >= 0),
  revision     INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0),
  name         TEXT NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  CONSTRAINT shopping_trips_id_user_unique UNIQUE (id, user_id),
  CONSTRAINT shopping_trips_name_valid CHECK (
    char_length(name) BETWEEN 1 AND 100 AND
    name = btrim(name, U&'\0009\000A\000B\000C\000D\0020\00A0\1680\2000\2001\2002\2003\2004\2005\2006\2007\2008\2009\200A\2028\2029\202F\205F\3000\FEFF')
  ),
  CONSTRAINT shopping_trips_completion_matches_status CHECK (
    (status = 'active' AND completed_at IS NULL) OR
    (status = 'completed' AND completed_at IS NOT NULL)
  )
);

CREATE TABLE IF NOT EXISTS cartcheck.trip_items (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         BIGINT NOT NULL,
  trip_id         BIGINT NOT NULL,
  product_id      BIGINT,
  name            TEXT NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 120),
  category        TEXT NOT NULL CHECK (length(btrim(category)) BETWEEN 1 AND 80),
  quantity        NUMERIC(12, 3) NOT NULL CHECK (quantity > 0),
  unit_label      TEXT CHECK (unit_label IS NULL OR length(btrim(unit_label)) BETWEEN 1 AND 24),
  estimated_total NUMERIC(12, 2) CHECK (estimated_total IS NULL OR estimated_total >= 0),
  actual_total    NUMERIC(12, 2) CHECK (actual_total IS NULL OR actual_total >= 0),
  bought          BOOLEAN NOT NULL DEFAULT false,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT trip_items_trip_owner_fk
    FOREIGN KEY (trip_id, user_id)
    REFERENCES cartcheck.shopping_trips(id, user_id) ON DELETE CASCADE,
  CONSTRAINT trip_items_product_owner_fk
    FOREIGN KEY (product_id, user_id)
    REFERENCES cartcheck.products(id, user_id) ON DELETE RESTRICT,
  CONSTRAINT trip_items_one_product_per_trip UNIQUE (trip_id, product_id)
);

CREATE INDEX IF NOT EXISTS sessions_user_id_idx
  ON cartcheck.sessions (user_id);
CREATE INDEX IF NOT EXISTS sessions_expires_at_idx
  ON cartcheck.sessions (expires_at);
CREATE INDEX IF NOT EXISTS auth_action_tokens_user_purpose_idx
  ON cartcheck.auth_action_tokens (user_id, purpose);
CREATE INDEX IF NOT EXISTS auth_action_tokens_expires_at_idx
  ON cartcheck.auth_action_tokens (expires_at);
CREATE INDEX IF NOT EXISTS products_user_name_idx
  ON cartcheck.products (user_id, lower(name));
CREATE INDEX IF NOT EXISTS products_user_category_idx
  ON cartcheck.products (user_id, category);
CREATE INDEX IF NOT EXISTS shopping_trips_user_completed_idx
  ON cartcheck.shopping_trips (user_id, completed_at DESC);
CREATE INDEX IF NOT EXISTS shopping_trips_active_updated_idx
  ON cartcheck.shopping_trips (user_id, updated_at DESC, id DESC) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS trip_items_trip_id_idx
  ON cartcheck.trip_items (trip_id);
