-- Idempotent starter catalog. These are templates only: there are no prices
-- or shopper-owned records here. Existing labels are preserved on re-run.
INSERT INTO cartcheck.starter_products (code, name, category) VALUES
  ('produce-apples', 'Apples', 'Produce'),
  ('produce-bananas', 'Bananas', 'Produce'),
  ('produce-oranges', 'Oranges', 'Produce'),
  ('produce-mangoes', 'Mangoes', 'Produce'),
  ('produce-grapes', 'Grapes', 'Produce'),
  ('produce-watermelon', 'Watermelon', 'Produce'),
  ('produce-pineapple', 'Pineapple', 'Produce'),
  ('produce-avocado', 'Avocado', 'Produce'),
  ('produce-tomatoes', 'Tomatoes', 'Produce'),
  ('produce-potatoes', 'Potatoes', 'Produce'),
  ('produce-sweet-potatoes', 'Sweet potatoes', 'Produce'),
  ('produce-onions', 'Onions', 'Produce'),
  ('produce-garlic', 'Garlic', 'Produce'),
  ('produce-ginger', 'Ginger', 'Produce'),
  ('produce-carrots', 'Carrots', 'Produce'),
  ('produce-cabbage', 'Cabbage', 'Produce'),
  ('produce-lettuce', 'Lettuce', 'Produce'),
  ('produce-spinach', 'Spinach', 'Produce'),
  ('produce-broccoli', 'Broccoli', 'Produce'),
  ('produce-cauliflower', 'Cauliflower', 'Produce'),
  ('produce-bell-peppers', 'Bell peppers', 'Produce'),
  ('produce-chili-peppers', 'Chili peppers', 'Produce'),
  ('produce-cucumbers', 'Cucumbers', 'Produce'),
  ('produce-eggplant', 'Eggplant', 'Produce'),
  ('produce-squash', 'Squash', 'Produce'),
  ('produce-green-beans', 'Green beans', 'Produce'),
  ('produce-corn', 'Corn', 'Produce'),
  ('produce-mushrooms', 'Mushrooms', 'Produce'),
  ('produce-lemons', 'Lemons', 'Produce'),
  ('produce-limes', 'Limes', 'Produce'),
  ('produce-calamansi', 'Calamansi', 'Produce'),
  ('produce-coconut', 'Coconut', 'Produce'),
  ('produce-papaya', 'Papaya', 'Produce'),
  ('produce-guava', 'Guava', 'Produce'),
  ('produce-pears', 'Pears', 'Produce'),
  ('dairy-milk', 'Milk', 'Dairy & eggs'),
  ('dairy-evaporated-milk', 'Evaporated milk', 'Dairy & eggs'),
  ('dairy-condensed-milk', 'Condensed milk', 'Dairy & eggs'),
  ('dairy-yogurt', 'Yogurt', 'Dairy & eggs'),
  ('dairy-cheddar', 'Cheddar cheese', 'Dairy & eggs'),
  ('dairy-mozzarella', 'Mozzarella cheese', 'Dairy & eggs'),
  ('dairy-cream-cheese', 'Cream cheese', 'Dairy & eggs'),
  ('dairy-butter', 'Butter', 'Dairy & eggs'),
  ('dairy-margarine', 'Margarine', 'Dairy & eggs'),
  ('dairy-eggs', 'Eggs', 'Dairy & eggs'),
  ('dairy-cream', 'All-purpose cream', 'Dairy & eggs'),
  ('meat-chicken', 'Chicken', 'Meat & seafood'),
  ('meat-pork', 'Pork', 'Meat & seafood'),
  ('meat-beef', 'Beef', 'Meat & seafood'),
  ('meat-ground-beef', 'Ground beef', 'Meat & seafood'),
  ('meat-ground-pork', 'Ground pork', 'Meat & seafood'),
  ('meat-bacon', 'Bacon', 'Meat & seafood'),
  ('meat-ham', 'Ham', 'Meat & seafood'),
  ('meat-hotdogs', 'Hot dogs', 'Meat & seafood'),
  ('meat-sausage', 'Sausage', 'Meat & seafood'),
  ('seafood-fish', 'Fish fillet', 'Meat & seafood'),
  ('seafood-tuna-fresh', 'Fresh tuna', 'Meat & seafood'),
  ('seafood-shrimp', 'Shrimp', 'Meat & seafood'),
  ('seafood-squid', 'Squid', 'Meat & seafood'),
  ('seafood-canned-tuna', 'Canned tuna', 'Meat & seafood'),
  ('seafood-sardines', 'Canned sardines', 'Meat & seafood'),
  ('bakery-white-bread', 'White bread', 'Bakery'),
  ('bakery-whole-wheat-bread', 'Whole wheat bread', 'Bakery'),
  ('bakery-pan-de-sal', 'Pan de sal', 'Bakery'),
  ('bakery-buns', 'Burger buns', 'Bakery'),
  ('bakery-tortillas', 'Tortillas', 'Bakery'),
  ('pantry-rice', 'Rice', 'Pantry'),
  ('pantry-pasta', 'Pasta', 'Pantry'),
  ('pantry-instant-noodles', 'Instant noodles', 'Pantry'),
  ('pantry-oats', 'Rolled oats', 'Pantry'),
  ('pantry-flour', 'All-purpose flour', 'Pantry'),
  ('pantry-sugar', 'White sugar', 'Pantry'),
  ('pantry-brown-sugar', 'Brown sugar', 'Pantry'),
  ('pantry-salt', 'Salt', 'Pantry'),
  ('pantry-black-pepper', 'Black pepper', 'Pantry'),
  ('pantry-cooking-oil', 'Cooking oil', 'Pantry'),
  ('pantry-olive-oil', 'Olive oil', 'Pantry'),
  ('pantry-vinegar', 'Vinegar', 'Pantry'),
  ('pantry-soy-sauce', 'Soy sauce', 'Pantry'),
  ('pantry-fish-sauce', 'Fish sauce', 'Pantry'),
  ('pantry-oyster-sauce', 'Oyster sauce', 'Pantry'),
  ('pantry-tomato-sauce', 'Tomato sauce', 'Pantry'),
  ('pantry-tomato-paste', 'Tomato paste', 'Pantry'),
  ('pantry-coconut-milk', 'Coconut milk', 'Pantry'),
  ('pantry-peanut-butter', 'Peanut butter', 'Pantry'),
  ('pantry-jam', 'Fruit jam', 'Pantry'),
  ('pantry-honey', 'Honey', 'Pantry'),
  ('pantry-coffee', 'Coffee', 'Pantry'),
  ('pantry-tea', 'Tea', 'Pantry'),
  ('pantry-cereal', 'Breakfast cereal', 'Pantry'),
  ('pantry-crackers', 'Crackers', 'Pantry'),
  ('pantry-canned-corn', 'Canned corn', 'Pantry'),
  ('pantry-canned-beans', 'Canned beans', 'Pantry'),
  ('pantry-stock-cubes', 'Stock cubes', 'Pantry'),
  ('frozen-frozen-vegetables', 'Frozen vegetables', 'Frozen'),
  ('frozen-frozen-fries', 'Frozen fries', 'Frozen'),
  ('frozen-ice-cream', 'Ice cream', 'Frozen'),
  ('snacks-potato-chips', 'Potato chips', 'Snacks'),
  ('snacks-biscuits', 'Biscuits', 'Snacks'),
  ('snacks-chocolate', 'Chocolate', 'Snacks'),
  ('snacks-popcorn', 'Popcorn', 'Snacks'),
  ('beverages-bottled-water', 'Bottled water', 'Beverages'),
  ('beverages-orange-juice', 'Orange juice', 'Beverages'),
  ('beverages-soft-drink', 'Soft drink', 'Beverages'),
  ('household-dishwashing-liquid', 'Dishwashing liquid', 'Household'),
  ('household-laundry-detergent', 'Laundry detergent', 'Household'),
  ('household-toilet-paper', 'Toilet paper', 'Household'),
  ('household-trash-bags', 'Trash bags', 'Household'),
  ('produce-kangkong', 'Water spinach (kangkong)', 'Produce'),
  ('produce-pechay', 'Pechay', 'Produce'),
  ('produce-okra', 'Okra', 'Produce'),
  ('produce-sayote', 'Chayote (sayote)', 'Produce'),
  ('produce-sitaw', 'Yardlong beans (sitaw)', 'Produce'),
  ('produce-malunggay-leaves', 'Malunggay leaves', 'Produce'),
  ('produce-ampalaya', 'Ampalaya', 'Produce'),
  ('produce-upo', 'Upo', 'Produce'),
  ('dairy-powdered-milk', 'Powdered milk', 'Dairy & eggs'),
  ('meat-chicken-thigh', 'Chicken thigh', 'Meat & seafood'),
  ('meat-chicken-drumstick', 'Chicken drumstick', 'Meat & seafood'),
  ('meat-bangus', 'Milkfish (bangus)', 'Meat & seafood'),
  ('meat-tilapia', 'Tilapia', 'Meat & seafood'),
  ('seafood-dried-fish', 'Dried fish', 'Meat & seafood'),
  ('meat-whole-chicken', 'Whole chicken', 'Meat & seafood'),
  ('meat-pork-belly', 'Pork belly (liempo)', 'Meat & seafood'),
  ('meat-tocino', 'Tocino', 'Meat & seafood'),
  ('meat-longganisa', 'Longganisa', 'Meat & seafood'),
  ('seafood-galunggong', 'Galunggong', 'Meat & seafood'),
  ('produce-saba-bananas', 'Saba banana', 'Produce'),
  ('produce-lakatan-bananas', 'Lakatan banana', 'Produce'),
  ('pantry-bihon', 'Bihon noodles', 'Pantry'),
  ('pantry-pancit-canton', 'Pancit canton', 'Pantry'),
  ('pantry-mung-beans', 'Mung beans (monggo)', 'Pantry'),
  ('pantry-bagoong', 'Bagoong', 'Pantry'),
  ('pantry-regular-milled-rice', 'Regular milled rice', 'Pantry'),
  ('pantry-dinorado-rice', 'Dinorado rice', 'Pantry'),
  ('pantry-sinandomeng-rice', 'Sinandomeng rice', 'Pantry'),
  ('pantry-glutinous-rice', 'Glutinous rice (malagkit)', 'Pantry'),
  ('pantry-cornstarch', 'Cornstarch', 'Pantry'),
  ('pantry-corn-grits', 'Corn grits', 'Pantry'),
  ('pantry-banana-ketchup', 'Banana ketchup', 'Pantry'),
  ('pantry-coconut-cream', 'Coconut cream', 'Pantry'),
  ('beverages-instant-coffee', 'Instant coffee', 'Beverages'),
  ('beverages-three-in-one-coffee', '3-in-1 coffee', 'Beverages'),
  ('pantry-cup-noodles', 'Cup noodles', 'Pantry'),
  ('household-fabric-conditioner', 'Fabric conditioner', 'Household'),
  ('pantry-canned-luncheon-meat', 'Canned luncheon meat', 'Pantry'),
  ('pantry-corned-beef', 'Canned corned beef', 'Pantry'),
  ('household-toothbrush', 'Toothbrush', 'Household'),
  ('frozen-fish-balls', 'Frozen fish balls', 'Frozen'),
  ('household-hair-conditioner', 'Hair conditioner', 'Household'),
  ('snacks-banana-chips', 'Banana chips', 'Snacks'),
  ('meat-pork-shoulder-kasim', 'Pork shoulder (kasim)', 'Meat & seafood'),
  ('beverages-powdered-juice', 'Powdered juice drink', 'Beverages'),
  ('beverages-chocolate-drink', 'Chocolate drink powder', 'Beverages'),
  ('household-sanitary-pads', 'Sanitary pads', 'Household'),
  ('household-bath-soap', 'Bath soap', 'Household'),
  ('household-shampoo', 'Shampoo', 'Household'),
  ('household-toothpaste', 'Toothpaste', 'Household'),
  ('household-bleach', 'Bleach', 'Household'),
  ('household-facial-tissues', 'Facial tissues', 'Household')
ON CONFLICT (code) DO NOTHING;
